title: "&f[&a战桥&f]"

scoreboard-title: "&a战桥"

# 是否保存玩家背包
save-playerInventory:  true




game-logo: "&l&cW&6a&er&aB&br&9i&cd&ag&ee"

join-menu:
  cw:
    buttonImg:
      type: "path"
      path: "textures/ui/icon_recipe_item"
    rooms:
      - 测试房间